name: 'se_resnet50_unet'
batch_size: 1
optimizer: 'adam'
epochs: 15
train_percent: 0.7
learning_rate: 0.001
momentum: 0.9
loss_fn: 'rmse'
encoder:
  name: se_resnet50
  in_channels: 4
  img_width: 640
  img_height: 480
decoder:
  attention: 'cbam'
