name: cbam_resnet50-pointnet
batch_size: 4
embedding_dim: 1024
sequence_len: 2048
img_backbone:
  name: cbam_resnet50
  img_width: 640
  img_height: 480
point_cloud_backbone:
  name: pointnet
  num_points: 1024
