name: se_resnet50-ndtnet
batch_size: 4
embedding_dim: 1024
sequence_len: 2048
img_backbone:
  name: se_resnet50
  img_width: 1920
  img_height: 1080
point_cloud_backbone:
  name: ndtnet
  num_points: 60000
