name: se_resnet50-ndtnet
batch_size: 4
epochs: 200
embedding_dim: 1024
sequence_len: 2048
lr: 0.001
img_backbone:
  name: se_resnet50
  in_channels: 4
  img_width: 1280
  img_height: 720
  num_img_features: 300
point_cloud_backbone:
  name: ndtnet
  num_points: 60000
  num_point_features: 1000
  point_dim: 3
  feature_dim: 1024
neck:
  name: vilbert
head:
  name: transformer
  grid_x: 200
  grid_y: 200
  grid_z: 16
