name: 'se_resnet50_unet'
batch_size: 16
optimizer: 'adam'
epochs: 15
train_percent: 0.7
val_percent: 0.2
test_percent: 0.1
learning_rate: 0.001
momentum: 0.9
loss_fn: 'rmse'
encoder:
  name: se_resnet50
  in_channels: 4
  img_width: 640
  img_height: 480
  with_dropout: True
decoder:
  attention: 'cbam'
