FROM nvidia/cuda:12.2.2-devel-ubuntu22.04

# install python and pip
RUN apt update
RUN apt install -y python3 python3-pip git

WORKDIR /
# install pytorch
RUN pip3 install torch
# install torchvision fork
RUN git clone https://github.com/carlostojal/vision.git
WORKDIR /vision
RUN python setup.py install

# copy the app
COPY . /app
WORKDIR /app

# run the image pre-training
CMD ["python3", "tools/img_pretrain.py"]
